### PR TITLE
RxJava support for batching methods

### LINKED ISSUE #110: findBatch doesn't work with RX API
The findBatch operation calls the result handler multiple times with each document in a batch. When finished, it sends a null object. This doesn't work with the RX API as it generates code that returns a Single since the result handler only mentions one document. So all we ever get is the first document instead of an observable stream of documents.

Perhaps a batch read stream should be created instead. Actually a batch write stream would be nice too. Such an implementation would diverge from the current service proxy api but would be very useful in dealing with large datasets with RX and in general.

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes #110 

The `xxxBatch` methods implementation use async result handlers incorrectly: such handlers should be called just once.

Instead, they should return a `ReadStream`, which brings:
- backpressure support
- RxJava support (via `ReadStream.toFlowable`)

Note that `MongoService` cannot implement them since `ReadStream` are not supported in service proxies.

### CODE REVIEW

**Comment by tsegismont** [comment]
If/when this is merged, the breaking changes page for 3.5.1 must be updated

**Comment by tsegismont** [comment]
Also, this PR fixes a context issue: in the previous implementation of `xxxBatch` methods, the callbacks would be invoked on Mongo driver threads.

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/MongoClient.java [hunk 1]
```diff
@@ -262,10 +263,8 @@ MongoClient bulkWriteWithOptions(String collection, List<BulkOperation> operatio
    *
    * @param collection  the collection
    * @param query  query used to match documents
-   * @param resultHandler  will be provided with each found document
    */
-  @Fluent
-  MongoClient findBatch(String collection, JsonObject query, Handler<AsyncResult<JsonObject>> resultHandler);
+  ReadStream<JsonObject> findBatch(String collection, JsonObject query);
```
Comment (cescoffier) [inline vertx-mongo-client/src/main/java/io/vertx/ext/mongo/MongoClient.java]: This is a breaking change, so we need to mention it in the breaking change list from 3.5.0 to 3.5.1.

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/MongoClient.java [hunk 2]
```diff
@@ -262,10 +263,8 @@ MongoClient bulkWriteWithOptions(String collection, List<BulkOperation> operatio
    *
    * @param collection  the collection
    * @param query  query used to match documents
-   * @param resultHandler  will be provided with each found document
```
Comment (cescoffier) [inline vertx-mongo-client/src/main/java/io/vertx/ext/mongo/MongoClient.java]: @return missing in the javadoc.

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java [hunk 3]
```diff
@@ -651,44 +635,31 @@ public MongoClient dropIndex(String collection, String indexName, Handler<AsyncR
...
-        distinctValues.forEach(valueBlock, callbackWhenFinished);
-      } catch (Exception unhandledEx) {
-        resultHandler.handle(Future.failedFuture(unhandledEx));
-      }
+  public ReadStream<JsonObject> distinctBatchWithQuery(String collection, String fieldName, String resultClassname, JsonObject query) {
+    try {
+      MongoIterable<JsonObject> distinctValues = findDistinctValuesWithQuery(collection, fieldName, resultClassname, query)
+        .map(value -> new JsonObject().put(fieldName, value));
+      return new MongoIterableStream(vertx.getOrCreateContext(), distinctValues);
+    } catch (ClassNotFoundException e) {
```
Comment (cescoffier) [inline vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java]: Wondering about Java 9

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java [hunk 4]
```diff
@@ -710,25 +681,17 @@ private void convertMongoIterable(MongoIterable iterable, Handler<AsyncResult<Js
...
-    final Class resultClass;
-    try {
-      resultClass = Class.forName(resultClassname);
-    } catch (ClassNotFoundException e) {
-      resultHandler.handle(Future.failedFuture(e));
-      return null;
-    }
     MongoCollection<JsonObject> mongoCollection = getCollection(collection);
-    return mongoCollection.distinct(fieldName, bquery, resultClass);
+    return mongoCollection.distinct(fieldName, bquery, Class.forName(resultClassname));
```
Comment (cescoffier) [inline vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java]: Don't use Class.forName, but this.getClass().getClassloader().load(resultClassname);

Class.forName hijacks the classloader hierarchy to delegate to the application classloader (classpath)

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java [hunk 5]
```diff
@@ -0,0 +1,186 @@
...
+import java.util.Deque;
+import java.util.List;
+import java.util.concurrent.atomic.AtomicReference;
+
+/**
+ * @author Thomas Segismont
+ */
+class MongoIterableStream implements ReadStream<JsonObject> {
+
+  private static final int BATCH_SIZE = 10;
```
Comment (cescoffier) [inline vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java]: Should it be configurable? I'm not a mongo expert.

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java [hunk 6]
```diff
@@ -0,0 +1,186 @@
...
+
+  @Override
+  public synchronized MongoIterableStream exceptionHandler(Handler<Throwable> handler) {
+    checkClosed();
+    this.exceptionHandler = handler;
+    return this;
+  }
+
+  private void checkClosed() {
+    if (closed) {
```
Comment (cescoffier) [inline vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java]: For safety, should be closed mark as volatile or the method also synchronized.
I understand that all access are made when holding the monitor lock, it's just in case....

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java [hunk 7]
```diff
@@ -0,0 +1,186 @@
...
+  @Override
+  public synchronized MongoIterableStream handler(Handler<JsonObject> handler) {
+    checkClosed();
+    if (handler == null) {
+      close();
+    } else {
+      dataHandler = handler;
+      SingleResultCallback<AsyncBatchCursor<JsonObject>> callback = (result, t) -> {
+        context.runOnContext(v -> {
+          synchronized (this) {
```
Comment (cescoffier) [inline vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java]: Should be MongoIterableStream.this. `this` here references the lambda.

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java [hunk 8]
```diff
@@ -0,0 +1,186 @@
...
+      } catch (Exception e) {
+        close();
+        handleException(e);
+      }
+    }
+    return this;
+  }
+
+  private boolean canRead() {
+    return !paused && !closed;
```
Comment (cescoffier) [inline vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java]: Same comment as above about volatile and synchronized.

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java [hunk 9]
```diff
@@ -0,0 +1,186 @@
...
+    context.<List<JsonObject>>executeBlocking(fut -> {
+      batchCursor.next((result, t) -> {
+        if (t != null) {
+          fut.fail(t);
+        } else {
+          fut.complete(result == null ? Collections.emptyList() : result);
+        }
+      });
+    }, false, ar -> {
+      synchronized (this) {
```
Comment (cescoffier) [inline vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java]: You should lock on the right object.

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java [hunk 10]
```diff
@@ -0,0 +1,186 @@
...
+          }
+        } else {
+          close();
+          handleException(ar.cause());
+        }
+      }
+    });
+  }
+
+  private void handleException(Throwable cause) {
```
Comment (cescoffier) [inline vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java]: should it be synchronized ? The exception handler can be updated.

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java [hunk 11]
```diff
@@ -0,0 +1,186 @@
...
+  public synchronized MongoIterableStream endHandler(Handler<Void> handler) {
+    endHandler = handler;
+    return this;
+  }
+
+  private void close() {
+    closed = true;
+    AtomicReference<AsyncBatchCursor> cursorRef = new AtomicReference<>();
+    context.executeBlocking(fut -> {
+      synchronized (this) {
```
Comment (cescoffier) [inline vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java]: Synchronize on the outer object.

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java [hunk 12]
```diff
@@ -0,0 +1,186 @@
...
+    }
+  }
+
+  @Override
+  public synchronized MongoIterableStream endHandler(Handler<Void> handler) {
+    endHandler = handler;
+    return this;
+  }
+
+  private void close() {
```
Comment (cescoffier) [inline vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java]: should it be synchronized?

File: vertx-mongo-service/src/main/java/io/vertx/ext/mongo/MongoService.java [hunk 13]
```diff
@@ -99,16 +101,20 @@ MongoService bulkWriteWithOptions(String collection, List<BulkOperation> operati
   MongoService find(String collection, JsonObject query, Handler<AsyncResult<List<JsonObject>>> resultHandler);
 
   @Override
-  @Fluent
-  MongoService findBatch(String collection, JsonObject query, Handler<AsyncResult<JsonObject>> resultHandler);
+  @GenIgnore
+  default ReadStream<JsonObject> findBatch(String collection, JsonObject query) {
```
Comment (cescoffier) [inline vertx-mongo-service/src/main/java/io/vertx/ext/mongo/MongoService.java]: What's the reason behind this "stub" implementation?

File: vertx-mongo-service/src/main/java/io/vertx/ext/mongo/impl/MongoServiceImpl.java [hunk 14]
```diff
@@ -165,13 +159,6 @@ public MongoService findWithOptions(String collection, JsonObject query, FindOpt
...
 
-  @Override
-  public MongoService findBatchWithOptions(String collection, JsonObject query, FindOptions options,
-      Handler<AsyncResult<JsonObject>> resultHandler) {
-    client.findBatchWithOptions(collection, query, options, resultHandler);
-    return this;
-  }
-
   @Override
   @Fluent
```
Comment (cescoffier) [inline vertx-mongo-service/src/main/java/io/vertx/ext/mongo/impl/MongoServiceImpl.java]: Can we remove the @Fluent in this class. It should not be used.

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/MongoClient.java (hunk 1 above)
Comment (tsegismont) [reply vertx-mongo-client/src/main/java/io/vertx/ext/mongo/MongoClient.java]: 👍

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java (hunk 3 above)
Comment (tsegismont) [reply vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java]: What do you mean?

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java (hunk 4 above)
Comment (tsegismont) [reply vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java]: I didn't want to change the original code but, fine, I'll do it.

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java (hunk 5 above)
Comment (tsegismont) [reply vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java]: Good question, wdyt @karianna ?

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java (hunk 6 above)
Comment (tsegismont) [reply vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java]: I prefer not to make it volatile. As you noticed, it's guarded by the stream instance, and we'll ruin the benefits of biased locking otherwise.

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java (hunk 7 above)
Comment (tsegismont) [reply vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java]: No, it's fine. See https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.27.2

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java (hunk 8 above)
Comment (tsegismont) [reply vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java]: Also guarded by the stream instance

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java (hunk 9 above)
Comment (tsegismont) [reply vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java]: `this` references the stream instance

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java (hunk 10 above)
Comment (tsegismont) [reply vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java]: `handleException` is always called from a synchronized method or block. The exception handler is guarded by the stream instance

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java (hunk 12 above)
Comment (tsegismont) [reply vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java]: Same, always called from synchronized method or block.

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java (hunk 11 above)
Comment (tsegismont) [reply vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java]: `this` references the stream instance

File: vertx-mongo-service/src/main/java/io/vertx/ext/mongo/impl/MongoServiceImpl.java (hunk 14 above)
Comment (tsegismont) [reply vertx-mongo-service/src/main/java/io/vertx/ext/mongo/impl/MongoServiceImpl.java]: What do you mean?

File: vertx-mongo-service/src/main/java/io/vertx/ext/mongo/MongoService.java (hunk 13 above)
Comment (tsegismont) [reply vertx-mongo-service/src/main/java/io/vertx/ext/mongo/MongoService.java]: The generated `MongoServiceVertxEBProxy` will not have these methods (`@GenIgnore`) but still implements `MongoService`. So we need a default impl.

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java (hunk 3 above)
Comment (cescoffier) [reply vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java]: We are loading a class using the current classloader. So it should work with Java 9 (module-less). However, it won't work if you attempt to load a class from another module. I guess it's fine (it's the module semantic), it just may be confusing.

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java (hunk 7 above)
Comment (cescoffier) [reply vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java]: So lambada and nested classes have a very different semantic on this. Confusing.... but ok.

File: vertx-mongo-service/src/main/java/io/vertx/ext/mongo/impl/MongoServiceImpl.java (hunk 14 above)
Comment (cescoffier) [reply vertx-mongo-service/src/main/java/io/vertx/ext/mongo/impl/MongoServiceImpl.java]: @Fluent on a method in an implementation class is needed.

**Comment by tsegismont** [comment]
@cescoffier PR updated. Also, I'm working on a doc update: some examples use deprecated methods, and `findBatch` is not clearly documented.

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java (hunk 5 above)
Comment (karianna) [reply vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java]: Yes please :-)

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java (hunk 6 above)
Comment (karianna) [reply vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java]: Worth adding a comment to that effect

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java (hunk 8 above)
Comment (karianna) [reply vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java]: comment this again for follow on developers

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java (hunk 9 above)
Comment (karianna) [reply vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java]: comment this again for follow on developers or use an explicit lock mechanism

**Comment by tsegismont** [comment]
@cescoffier @karianna I made the batch size configurable and updated the doc accordingly. I addressed all of your comments.

**Comment by karianna** [comment]
Thanks - I'll ping @johnoliver on Monday to go through a bunch of these.  I'm listed as a maintainer, but the reality is that John does the real coding :-)

**Comment by tsegismont** [comment]
@johnoliver any comment?

**Comment by karianna** [comment]
@tsegismont Sorry, I've been keeping John busy on jClarity stuff :-D.  We'll go through all of the openPRs and issues sometime this week when customer work dies down.

**Comment by tsegismont** [comment]
Perfect.

2017-12-19 17:46 GMT+01:00 Martijn Verburg <notifications@github.com>:

**Comment by johnoliver** [comment]
Think this looks good to me, think my only comment would be that all the synchronising may be clearer if there was an explicit lock object created rather than using `synchronized(this)` inside lambdas, which has caused some confusion. But I dont think we need to hold up the PR for that.

Thanks
