### PR TITLE
Fix #44.

### LINKED ISSUE #44: Creating a new document with an _id field fails
The current logic of saveWithOptions, says that if the document to save has an _id then the query gets changed to a "replaceOne", if the db then does not have an existing entry with that _id no document will be saved.

### PR DESCRIPTION
**Pull request by johnoliver**
Allow saving of documents with an existing _id

### CODE REVIEW

File: vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java [hunk 1]
```diff
@@ -100,7 +100,10 @@ public void close() {
       JsonObject encodedDocument = encodeKeyWhenUseObjectId(document);
       filter.put(ID_FIELD, encodedDocument.getValue(ID_FIELD));
 
-      coll.replaceOne(wrap(filter), encodedDocument, convertCallback(resultHandler, result -> null));
+      com.mongodb.client.model.UpdateOptions updateOptions = new com.mongodb.client.model.UpdateOptions()
+              .upsert(true);
+
+      coll.replaceOne(wrap(filter), encodedDocument, updateOptions, convertCallback(resultHandler, result -> null));
```
Comment (karianna) [inline vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java]: I'm going to bite my tongue about coll vs collection naming (I know, I know, we're following what's previously there) :-)
